# Generated by Django 2.2.14 on 2020-08-14 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mykitchen.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_auto_20200810_1615'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Household name', max_length=50)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kitchen Fixtures', max_length=50)),
                ('storage_temperature', models.IntegerField(blank=True, help_text='Storage Temperatures')),
                ('editted_by', models.ForeignKey(on_delete=models.SET(mykitchen.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mykitchen.Household')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('remarks', models.TextField(blank=True, max_length=600)),
                ('expiry_date', models.DateField()),
                ('threshold', models.IntegerField()),
                ('package', models.CharField(choices=[('bar', 'Bar'), ('bottle', 'Bottle'), ('box', 'Box'), ('pack', 'Pack'), ('roll', 'Roll'), ('tin', 'Tin')], default='pack', help_text='Food Packages', max_length=7)),
                ('editted_by', models.ForeignKey(on_delete=models.SET(mykitchen.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mykitchen.Location')),
            ],
        ),
    ]
