# Generated by Django 2.2.14 on 2020-08-23 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mykitchen.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20200810_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name to identify your household', max_length=50)),
                ('owner', models.ForeignKey(on_delete=models.SET(mykitchen.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kitchen Fixtures', max_length=50)),
                ('storage_temperature', models.IntegerField(blank=True, help_text='deg Celsius')),
                ('storage_type', models.CharField(choices=[('cabinet', 'Cabinet'), ('cupboard', 'Cupboard'), ('counter-top', 'Counter'), ('fridge', 'Refridgerator'), ('freezer', 'Freezer'), ('pantry', 'Pantry'), ('others', 'Others')], default='cupboard', help_text='Storage Location Types', max_length=11)),
                ('edited_by', models.ForeignKey(on_delete=models.SET(mykitchen.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mykitchen.Household')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household', to='mykitchen.Household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='number of packages')),
                ('remarks', models.TextField(blank=True, max_length=600)),
                ('expiry_date', models.DateField(blank=True, help_text='Enter date in YYYY-MM-DD format', null=True)),
                ('threshold', models.IntegerField(help_text='Number of days before expiry date to notify me')),
                ('package', models.CharField(choices=[('bar', 'Bar'), ('bottle', 'Bottle'), ('box', 'Box'), ('pack', 'Pack'), ('roll', 'Roll'), ('tin', 'Tin')], default='pack', help_text='Food Packages', max_length=7)),
                ('edited_by', models.ForeignKey(on_delete=models.SET(mykitchen.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mykitchen.StorageLocation')),
            ],
        ),
    ]
