# Generated by Django 2.2.14 on 2020-08-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykitchen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='editted_by',
            new_name='edited_by',
        ),
        migrations.AlterField(
            model_name='location',
            name='storage_temperature',
            field=models.IntegerField(blank=True, help_text='Storage Temperatures in degC'),
        ),
    ]
