# Generated by Django 2.2.14 on 2020-08-16 15:50
from django.contrib.auth.models import Group, Permission
from django.db import migrations


def create_and_add_group_permissions(apps, schema_editor):
    owner_group, created = Group.objects.get_or_create(name='owner_group')
    member_group, created = Group.objects.get_or_create(name='member_group')

    permission1 = Permission.objects.get(name='Can view household')
    permission2 = Permission.objects.get(name='Can add household')
    permission3 = Permission.objects.get(name='Can change household')
    permission4 = Permission.objects.get(name='Can delete household')
    permission5 = Permission.objects.get(name='Can view member')
    permission6 = Permission.objects.get(name='Can add member')
    permission7 = Permission.objects.get(name='Can change member')
    permission8 = Permission.objects.get(name='Can delete member')
    permission9 = Permission.objects.get(name='Can view storage location')
    permission10 = Permission.objects.get(name='Can add storage location')
    permission11 = Permission.objects.get(name='Can change storage location')
    permission12 = Permission.objects.get(name='Can delete storage location')
    permission13 = Permission.objects.get(name='Can view food item')
    permission14 = Permission.objects.get(name='Can add food item')
    permission15 = Permission.objects.get(name='Can change food item')
    permission16 = Permission.objects.get(name='Can delete food item')
    owner_permissions = [permission1, permission2, permission3,
                   permission4, permission5, permission6,
                   permission7, permission8, permission9,
                   permission10, permission11, permission12,
                   permission13, permission14, permission15,
                   permission16]

    member_permissions = [permission9, permission10, permission11, permission12,
                          permission13, permission14, permission15, permission16]

    if created:
        owner_group.permissions.set(owner_permissions)
        member_group.permissions.set(member_permissions)
    

class Migration(migrations.Migration):

    dependencies = [
        ('mykitchen', '0003_auto_20200815_0838'),
    ]

    operations = [
        migrations.RunPython(create_and_add_group_permissions),
    ]
