# Generated by Django 2.2.14 on 2020-08-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykitchen', '0004_auto_20200816_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='storage_type',
            field=models.CharField(choices=[('cabinet', 'Cabinet'), ('cupboard', 'Cupboard'), ('counter-top', 'Counter'), ('fridge', 'Refridgerator'), ('freezer', 'Freezer'), ('pantry', 'Pantry'), ('others', 'Others')], default='cupboard', help_text='Storage Location Types', max_length=11),
        ),
        migrations.AlterField(
            model_name='household',
            name='name',
            field=models.CharField(help_text='Name to identify your household', max_length=50),
        ),
    ]
