# Generated by Django 2.2.14 on 2020-08-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykitchen', '0006_auto_20200818_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelocation',
            name='storage_temperature',
            field=models.IntegerField(blank=True, help_text='deg Celsius'),
        ),
    ]
