# Generated by Django 2.2.14 on 2020-08-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykitchen', '0007_auto_20200818_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Enter date in YYYY-MM-DD format', null=True),
        ),
    ]
