# Generated by Django 2.2.14 on 2020-08-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykitchen', '0008_auto_20200819_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.IntegerField(help_text='number of packages'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='threshold',
            field=models.IntegerField(help_text='Number of days before expirydate to notify me'),
        ),
    ]
