# Generated by Django 2.2.14 on 2020-08-08 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500)),
                ('weight_per_pack', models.FloatField()),
                ('qty_per_pack', models.IntegerField(blank=True, null=True)),
                ('barcode_spec', models.CharField(blank=True, max_length=3)),
                ('barcode_no', models.BigIntegerField(blank=True, null=True)),
                ('image', models.URLField()),
                ('root_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_edited', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Country')),
                ('subcategory', models.ManyToManyField(to='products.Subcategory')),
                ('usage', models.ManyToManyField(to='products.Usage')),
            ],
        ),
    ]
