# Generated by Django 2.2.14 on 2020-08-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200810_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='multiplier',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=5),
        ),
    ]
